version: '3'
services: 
    db:
        build: 
            dockerfile: Dockerfile.db
            context: .
        ports: 
            - "5432:5432" 
        volumes: 
            - postgres_volume:/var/lib/postgresql/data
    api:
        build: .
        depends_on: 
            - db
        ports: 
           - "8090:8000"

volumes:
  postgres_volume:
    driver: local
